apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - podinfo.yaml
  - ./apps.ibb/deployment-ibb-frontend.yml
  - ./apps.ibb/svc-ibb-frontend.yml
  - ./cronjobs/ecr-cronjob.yml
